// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC--w43ROOt9LrzKW_Ji1ZLD90mU8LBixI',
    appId: '1:105283033477:web:1358d978eb94d6f93e4cec',
    messagingSenderId: '105283033477',
    projectId: 'fotoz-3a8a4',
    authDomain: 'fotoz-3a8a4.firebaseapp.com',
    storageBucket: 'fotoz-3a8a4.firebasestorage.app',
    measurementId: 'G-6GYYPFG02Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMDNTztsOs9wJRn4LcmdrmlBAElTl6eY',
    appId: '1:105283033477:android:71d124a22855bd943e4cec',
    messagingSenderId: '105283033477',
    projectId: 'fotoz-3a8a4',
    storageBucket: 'fotoz-3a8a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD9q6gIReAS6WpAK9FdlHIc14jq8h3IH4',
    appId: '1:105283033477:ios:e57bc01c85aedc593e4cec',
    messagingSenderId: '105283033477',
    projectId: 'fotoz-3a8a4',
    storageBucket: 'fotoz-3a8a4.firebasestorage.app',
    iosBundleId: 'com.example.fotoz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD9q6gIReAS6WpAK9FdlHIc14jq8h3IH4',
    appId: '1:105283033477:ios:e57bc01c85aedc593e4cec',
    messagingSenderId: '105283033477',
    projectId: 'fotoz-3a8a4',
    storageBucket: 'fotoz-3a8a4.firebasestorage.app',
    iosBundleId: 'com.example.fotoz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC--w43ROOt9LrzKW_Ji1ZLD90mU8LBixI',
    appId: '1:105283033477:web:f41a1b6ee40a60f13e4cec',
    messagingSenderId: '105283033477',
    projectId: 'fotoz-3a8a4',
    authDomain: 'fotoz-3a8a4.firebaseapp.com',
    storageBucket: 'fotoz-3a8a4.firebasestorage.app',
    measurementId: 'G-K7X3KC9YKR',
  );
}
